- name: 'bug'
  color: 'd62437'
- name: 'chore'
  color: 'e6e6e6'
- name: 'dependencies'
  color: 'f7ff19'
- name: 'documentation'
  color: '008ef5'
- name: 'duplicate'
  color: 'd4bcbf'
- name: 'enhancement'
  color: '25c4db'
- name: 'has PR'
  color: '8627c4'
- name: 'help wanted'
  color: 'f9ff45'
- name: 'invalid'
  color: 'e68069'
- name: 'performance'
  color: '3ae846'
- name: 'priority: high'
  color: 'ff2432'
- name: 'refactor'
  color: 'f0b40e'
- name: 'semver: major'
  color: 'ff7236'
- name: 'semver: minor'
  color: 'ff8957'
- name: 'semver: patch'
  color: 'ffae8c'
- name: 'typings'
  color: '28629c'
- name: 'wontfix'
  color: '999999'
