/**
 * Constants.
 */
export const Constants = {
    BASSBOOST_INTENSITY_MULTIPLIER: 0.15,
    DEFAULT_MAX_SFX: 10000,
    EQ_BAND_COUNT: 15,
    TEXT_PERMISSIONS: [`VIEW_CHANNEL`, `SEND_MESSAGES`, `EMBED_LINKS`],
    TREBLE_INTENSITY_MULTIPLIER: 0.15,
    TREMOLO_VIBRATO_FREQUENCY: 5,
    VOICE_TIMEOUT: 5000
} as const;
