name: Lint

on:
  push:
  pull_request:

jobs:
  run-lint:
    name: Run Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16]

    steps:
       # Checkout repository.
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cache node modules.
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Setup node.
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      # Install packages.
      - name: Install packages
        run: npm i --also=dev

      # Run linters.
      - name: Run linters
        run: npm run lint